image: maven:3.5.4-jdk-8-alpine

compile:
    stage: build
    script:
        - cd src
        - mvn compile


verify:
    script:
      - cd docker/dev
      - docker-compose up
      - cd ../../src
      - mvn clean verify