image: maven:3.5.4-jdk-8-alpine

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose

compile:
    stage: build
    script:
        - cd src
        - mvn compile


verify:
    script:
      - cd docker/dev
      - docker-compose up
      - cd ../../src
      - mvn clean verify