image: maven:3.5.0-jdk-8-alpine

services:
  - postgres:latest

variables:
  POSTGRES_DB: db_myerp
  POSTGRES_USER: usr_myerp
  POSTGRES_PASSWORD: myerp

before_script:
  - sudo apt-get install -y postgresql postgresql-client libpq-dev
  - psql docker/dev/init/db/docker-entrypoint-initdb.d/01_create_schema.sql docker/dev/init/db/docker-entrypoint-initdb.d/02_create_tables.sql docker/dev/init/db/docker-entrypoint-initdb.d/21_insert_data_demo.sql

compile:
    image: maven:3.5.4-jdk-8-alpine
    stage: build
    script:
        - cd src
        - mvn compile


verify:
    image: maven:3.5.4-jdk-8-alpine
    script:
      - cd src
      - mvn clean verify
