image: tmaier/docker-compose:latest

services:
  - docker:dind

variables:
  SPRING_PROFILES_ACTIVE: test-business

before_script:
  - docker info
  - docker-compose --version

compile:
    image: maven:3.5.4-jdk-8-alpine
    stage: build
    script:
        - cd src
        - mvn compile


verify:
    image: maven:3.5.4-jdk-8-alpine
    tags:
      - docker
    script:
      - cd docker/dev
      - docker-compose up
      - cd ../../src
      - mvn clean verify
      - docker-compose stop
      - docker-compose rm -v
