image: maven:3.5.0-jdk-8-alpine

services:
  - postgres:latest

variables:
  POSTGRES_DB: db_myerp
  POSTGRES_USER: usr_myerp
  POSTGRES_PASSWORD: myerp


connect:
  image: postgres
  script:
    # official way to provide password to psql: http://www.postgresql.org/docs/9.3/static/libpq-envars.html
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"

compile:
    image: maven:3.5.4-jdk-8-alpine
    stage: build
    script:
        - cd src
        - mvn compile


verify:
    image: maven:3.5.4-jdk-8-alpine
    script:
      - cd src
      - mvn clean verify
