image: docker:latest

services:
  - docker:dind

variables:
  SPRING_PROFILES_ACTIVE: test-business

before_script:
  - docker run -it docker /bin/sh
  - apk add --no-cache py-pip
  - pip install docker-compose

compile:
    image: maven:3.5.4-jdk-8-alpine
    stage: build
    script:
        - cd src
        - mvn compile


verify:
    image: maven:3.5.4-jdk-8-alpine
    script:
      - export DOCKER_HOST="tcp://localhost:2375"
      - cd docker/dev
      - docker-compose up
      - cd ../../src
      - mvn clean verify
      - docker-compose stop
      - docker-compose rm -v
